#
# Executes commands at the start of an interactive session.

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey "^R" history-incremental-search-backward

# TODO: source /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

export ANDROID_HOME=~/Library/Android/sdk
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="$PATH:/$HOME/Qt5.5.1/5.5/clang_64/bin"
export PATH="$PATH:/usr/local/share/dotnet"
eval $(/usr/libexec/path_helper -s)
