#
# Executes commands at the start of an interactive session.

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey "^R" history-incremental-search-backward

# Load Zsh tools for syntax highlighting and autosuggestions
HOMEBREW_FOLDER="/usr/local/share"
source "$HOMEBREW_FOLDER/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$HOMEBREW_FOLDER/zsh-autosuggestions/zsh-autosuggestions.zsh"

# Aliases for list commands with colorful output
alias lsc="colorls"
alias ls='ls -G'

eval $(/usr/libexec/path_helper -s)
eval "$(pyenv init -)"

# Manage multiple runtime versions with a single CLI tool
. /usr/local/opt/asdf/asdf.sh

# Kubernetes
export KUBE_EDITOR="vim"
[[ /usr/local/bin/kubectl ]] && source <(kubectl completion zsh)

alias k=kubectl
alias kcd='kubectl config set-context $(kubectl config current-context) --namespace '

# Golang
export GOPATH=$HOME/go
export PATH="$PATH:$(go env GOPATH)/bin"
