# Python -------------------------------------------------------------------------------------------

[[language]]
name = "python"
auto-format = true
language-servers = ["ruff", "ty"]
formatter = { command = "ruff", args = ["format", "-"] }

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ty]
command = "ty"
args = ["server"]

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python3"
args = ["-m", "debugpy.adapter"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [{ name = "entrypoint", completion = "filename", default = "." }]
args = { mode = "debug", program = "{0}" }

# Go -----------------------------------------------------------------------------------------------

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls", "golangci-lint-lsp"]

[language-server.gopls]
command = "gopls"
config = { "gofumpt" = true }

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

# Rust ---------------------------------------------------------------------------------------------

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.check]
command = "clippy"

# TypeScript / JavaScript --------------------------------------------------------------------------

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "npx", args = ["prettier", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "npx", args = ["prettier", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "npx", args = ["prettier", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "npx", args = ["prettier", "--stdin-filepath", "%{buffer_name}"] }

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config = { hostInfo = "helix", tsserver = { }, preferences = { }, format = { semicolons = "insert" } }

# C++ ----------------------------------------------------------------------------------------------

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }
language-servers = ["clangd"]

[language-server.clangd]
command = "clangd"
args = [
  "--background-index",
  "--clang-tidy",
  "--completion-style=detailed",
  "--header-insertion=iwyu"
]
