#!/usr/bin/env sh
# Install Homebrew packages I commonly use.

# Check for Homebrew and install if we don't have it
if test ! $(which brew); then
  read -p "Homebrew is not installed. Would you like to install it? (y/n): [n]" -n 1 -r; echo
  if [ "$REPLY" = "y" ]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    exit
  fi
fi

# Install packages
brew install openssl                     # OpenSSL SSL/TLS cryptography library
brew install readline                    # Software library that provides in-line editing and history capabilities
brew install xz                          # Compress or decompress FILEs in the .xz format
brew install zlib                        # General-purpose lossless data-compression library
brew install gpg2                        # Signing and verification for GNU Privacy Guard 2

brew install direnv                      # Load/unload environment variables based on $PWD
brew install zsh                         # Zsh is a shell designed for interactive use, although it is also a powerful scripting language
brew install zsh-syntax-highlighting     # Syntax highlighting for Zsh
brew install zsh-autosuggestions         # Autosuggestions for Zsh
brew install zsh-completions             # Additional completion definitions for Zsh https://github.com/zsh-users/zsh-completions
brew install tmux                        # Tmux is a "terminal multiplexer", it enables a number of terminals (or windows) to be accessed and controlled from a single terminal
brew install reattach-to-user-namespace  # http://www.economyofeffort.com/2013/07/29/reattach-to-user-namespace-the-fix-for-your-tmux-in-os-x-woes/
brew install terminal-notifier           # Send User Notifications on macOS from the command-line

brew install git                         # Git is a fast, scalable, distributed revision control system
brew install git-lfs                     # Git extension for versioning large files
brew install icdiff                      # icdiff: side-by-side highlighted command line diffs http://www.jefftk.com/icdiff
brew install gh                          # GitHub command-line tool https://github.com/cli/cli

brew install eza                         # a modern replacement for ls
brew install bat                         # A cat(1) clone with wings
brew install wget                        # GNU Wget is a free utility for non-interactive download of files from the Web
brew install htop                        # htop is an interactive text-mode process viewer for Unix systems
brew install btop                        # Resource monitor that shows usage and stats for processor, memory, disks, network and processes
brew install tree                        # Display directories as trees (with optional color/HTML output) http://mama.indstate.edu/users/ice/tree/
brew install mc                          # Terminal-based visual file manager
brew install nnn                         # nnn is a full-featured terminal file manager

brew install jsonpp                      # A fast command line JSON pretty printer. http://jmhodges.github.com/jsonpp/
brew install jq                          # Command-line JSON processor

brew install asdf                        # Manage multiple runtime versions with a single CLI tool https://asdf-vm.com/
brew install sqlite                      # A database engine, a library that software developers embed in their apps

brew install helix                       # Modern terminal editor https://helix-editor.com/

brew install dive                        # Tool for exploring each layer in a docker image https://github.com/wagoodman/dive
brew install minikube                    # Run a Kubernetes cluster locally https://minikube.sigs.k8s.io/
brew install kubernetes-cli              # Kubernetes command-line interface https://kubernetes.io/
brew install openshift-cli               # OpenShift command-line interface tools https://www.openshift.com/
brew install helm                        # Kubernetes package manager https://helm.sh/

brew install zola                        # Fast static site generator in a single binary with everything built-in. https://www.getzola.org/
brew install httpie                      # Modern command line HTTP client – user-friendly curl alternative with intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc. https://httpie.org
brew install mitmproxy                   # Intercept, modify, replay, save HTTP/S traffic https://mitmproxy.org

brew install ffmpeg                      # Play, record, convert, and stream audio and video
brew install youtube-dl                  # Command-line program to download videos from YouTube.com and other video sites http://rg3.github.io/youtube-dl/

brew install exercism                    # Level up your programming skills http://exercism.io/
