#!/usr/bin/env sh
# Install brew cask packages

brew cask install iterm2
brew cask install google-chrome
brew cask install chromium
brew cask install firefox
brew cask install slack
brew cask install virtualbox
brew cask install vagrant
brew cask install skype
brew cask install java
brew cask install flux
brew cask install atom
brew cask install dropbox
brew cask install dash
brew cask install alfred
