#!/usr/bin/env sh
# install brew cask packages

# Fonts
brew cask install font-fira-code
brew cask install font-jetbrains-mono

brew cask install forklift
brew cask install hiddenbar
brew cask install hiddenbar

# Development
brew cask install iterm2
brew cask install kitty

brew cask install docker
brew cask install minishift

brew cask install fork
brew cask install dash
brew cask install insomnia
brew cask install visual-studio-code
brew cask install postico

brew cask install openjdk
brew cask install jetbrains-toolbox
