#!/usr/bin/env sh
# Install homebrew packages

# Check for Homebrew
if test ! $(which brew); then
  read -p "Confirm installing Homebrew (y/n): [n]" -n 1 -r; echo
  if [ "$REPLY" = "y" ]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    exit
  fi
fi

# Install Cask
brew install caskroom/cask/brew-cask

brew install fasd
brew install the_silver_searcher
brew install wget
brew install htop
brew install watch
brew install git
brew install jsonpp
brew install terminal-notifier

brew install tmux
brew install reattach-to-user-namespace

brew install zsh