#!/usr/bin/env sh
# install brew cask packages

# Hardware
brew cask install gfxcardstatus

# Storage & Backups
brew cask install google-drive
brew cask install dropbox
brew cask install arq

# Software
brew cask install sizeup
brew cask install alfred
brew cask install cheatsheet
brew cask install 1password
brew cask install fantastical
brew cask install android-file-transfer

# Messengers
brew cask install slack
brew cask install skype

# Browsers
brew cask install google-chrome
brew cask install firefox
brew cask install opera
brew cask install twitter

# Design
brew cask install sketch
brew cask install sketch-tool
brew cask install sketch-toolbox

# Development
brew cask install iterm2

brew cask install docker
brew cask install kitematic

brew cask install visual-studio-code

brew cask install java
brew cask install jetbrains-toolbox

brew cask install devdocs
brew cask install postico
